name: Build & Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest # single OS, builds for all platforms
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build production webpack
        run: npm run dist

      - name: Build & Publish electron app (all platforms)
        run: npx electron-builder --publish always --win --linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
